<?xml version="1.0"?>
<robot name="Minotaur" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.44" />
  <xacro:property name="length" value="0.75" />
  <xacro:property name="height" value="0.2" />
  <xacro:property name="mastheight" value="0.74" />
  <xacro:property name="mastside" value="0.05" />
  <xacro:property name="wheelrad" value="0.16" />
  <xacro:property name="pi" value="3.1415" />
  <xacro:property name="clearance" value="0.15" />
  
  <xacro:property name="cameraSize" value="0.04"/>
  <xacro:property name="cameraMass" value="0.1"/>
  
  <xacro:include filename="$(find minotaur_description)/urdf/Minotaur.gazebo" />
  
	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>
	
	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>
	
	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>
	
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>
	
	<link name="base_link">
		<visual>
			<geometry>
				<box size="${width} ${length} ${height}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<geometry>
				<box size="${width} ${length} ${height}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="10"/>
	</link>
	
	<link name="front_end">
		<visual>
			<geometry>
				<cylinder length="${height}" radius="${width/2}"/>
			</geometry>
			<material name="blue"/>
			<origin xyz="0 0 0"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${height}" radius="${width/2}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>
	
	<joint name="front_base_joint" type="fixed">
		<parent link="base_link"/>
		<child link="front_end"/>
		<origin xyz="0 0.375 0"/>
	</joint>
	
	<link name="right_wheel">
		<visual>
			<origin rpy="0 ${pi/2} 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheelrad/2}" radius="${wheelrad}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin rpy="0 ${pi/2} 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="0.2" radius="${wheelrad}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="5"/>
	</link>
		
	<joint name="right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_wheel"/>
		<origin xyz="0.26 0.1 -0.09" rpy="${pi/2} 0 0"/>
		<limit effort="30" velocity="10.0"/>
	</joint>
	
	<transmission name="right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="right_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="right_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
	
	<link name="left_wheel">
		<visual>
			<origin rpy="0 ${pi/2} 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheelrad/2}" radius="${wheelrad}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin rpy="0 ${pi/2} 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="0.2" radius="${wheelrad}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="5"/>
	</link>
		
	<joint name="left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_wheel"/>
		<origin xyz="-0.26 0.1 -0.09" rpy="${pi/2} 0 0"/>
		<limit effort="30" velocity="10.0"/>
	</joint>
	
	<transmission name="left_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="left_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="left_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
  
<!-- This block provides the simulator (Gazebo) with information on a few additional
  physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
  <gazebo reference="left_wheel">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/White</material>
  </gazebo>
  
  <gazebo reference="right_wheel">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/White</material>
  </gazebo>
	
	<link name="right_mast">
		<visual>
			<geometry>
				<box size="${mastside} ${mastside} ${mastheight}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<geometry>
				<box size="${mastside} ${mastside} ${mastheight}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>
	
	<link name="left_mast">
		<visual>
			<geometry>
				<box size="${mastside} ${mastside} ${mastheight}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<geometry>
				<box size="${mastside} ${mastside} ${mastheight}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>
	
	<joint name="right_mast_joint" type="fixed">
		<parent link="base_link"/>
		<child link="right_mast"/>
		<origin xyz="0.195 0.1 0.47"/>
	</joint>
	
	<joint name="left_mast_joint" type="fixed">
		<parent link="base_link"/>
		<child link="left_mast"/>
		<origin xyz="-0.195 0.1 0.47"/>
	</joint>	
	
	<link name="mast_link">
		<visual>
			<geometry>
				<box size="0.34 ${mastside} ${mastside}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<geometry>
				<box size="0.34 ${mastside} ${mastside}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>
		
	<joint name="right_cam_joint" type="fixed">
		<parent link="right_mast"/>
		<child link="mast_link"/>
		<origin xyz="-0.0975 0 0.15"/>
	</joint>
	
	<joint name="left_cam_joint" type="fixed">
		<parent link="left_mast"/>
		<child link="mast_link"/>
		<origin xyz="0 0 0.15"/>
	</joint>
	
	<link name="caster_wheel">
		<visual>
			<origin rpy="0 ${pi/2} 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="0.1" radius="0.075"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin rpy="0 ${pi/2} 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="0.15" radius="0.075"/>
			</geometry>
		</collision>
		<inertial>
      <mass value="1"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
	</link>
	
	<joint name="caster_joint" type="continuous">
		<parent link="base_link"/>
		<child link="caster_wheel"/>
		<origin xyz="0 -0.35 -0.175" rpy="${pi/2} 0 0"/>
		<limit effort="30" velocity="10.0"/>
	</joint>
	
	<!-- This block connects the castor_joint joint to an actuator (motor), which informs both simulation and visualization of the robot -->
	
	<transmission name="caster_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="caster_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="caster_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
  
  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="0 0 0.02" rpy="${pi/6} 0 ${pi/2}"/>
    <parent link="mast_link"/>
    <child link="camera"/>
  </joint>

	<!-- Hokuyo Laser -->
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    		<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://minotaur_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.135" rpy="0 0 ${pi/2}"/>
    <parent link="front_end"/>
    <child link="hokuyo"/>
  </joint>

	
	<!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

</robot>
